language: ruby
cache:
  bundler: true

bundler_args: --without guard development

matrix:
  include:
    - rvm: 2.4.6
    - rvm: 2.5.5
    - rvm: 2.6.2
    - rvm: jruby-9.2.6.0 # ruby 2.5
      jdk: oraclejdk8
    - rvm: 2.4.6
      install: true # This skips 'bundle install'
      script: gem build rainbow && gem install *.gem

env:
  global:
    - JRUBY_OPTS=--debug
